{% set version = "0.24.1" %}

package:
  name: shelephant
  version: {{ version }}

source:
  url: https://github.com/tdegeus/shelephant/archive/v{{ version }}.tar.gz
  sha256: 189005e0a5b21cdb61ea45d7b2129f9b100b5d6cd2e69340396e05901df72ba3

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shelephant = shelephant.cli:_shelephant_main
    - shelephant_cp = shelephant.cli:_shelephant_cp_main
    - shelephant_diff = shelephant.cli:_shelephant_diff_main
    - shelephant_dump = shelephant.cli:_shelephant_dump_main
    - shelephant_hostinfo = shelephant.cli:_shelephant_hostinfo_main
    - shelephant_mv = shelephant.cli:_shelephant_mv_main
    - shelephant_parse = shelephant.cli:_shelephant_parse_main
    - shelephant_rm = shelephant.cli:_shelephant_rm_main

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools_scm
  run:
    - click
    - numpy >=1.15.0
    - platformdirs
    - prettytable
    - python >=3.10
    - pyyaml
    - tqdm

test:
  imports:
    - shelephant
  commands:
    - pip check
    - python -c "import shelephant; assert shelephant.version == '{{ version }}'"
    - shelephant --version | grep {{ version }}
    - shelephant_cp --version | grep {{ version }}
    - shelephant_diff --version | grep {{ version }}
    - shelephant_dump --version | grep {{ version }}
    - shelephant_hostinfo --version | grep {{ version }}
    - shelephant_mv --version | grep {{ version }}
    - shelephant_parse --version | grep {{ version }}
    - shelephant_rm --version | grep {{ version }}
  requires:
    - pip

about:
  home: https://github.com/tdegeus/shelephant
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dataset management
  description: Dataset management
  doc_url: https://shelephant.readthedocs.io
  dev_url: https://github.com/tdegeus/shelephant

extra:
  recipe-maintainers:
    - tdegeus
