{% set name = "shelephant" %}
{% set version = "0.13.0" %}
{% set sha256 = "849feb925672574e808560d00eb27a2231999e324ee5c622259886c188db16ac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shelephant_checksum = shelephant.cli.shelephant_checksum:main
    - shelephant_dump = shelephant.cli.shelephant_dump:main
    - shelephant_extract = shelephant.cli.shelephant_extract:main
    - shelephant_get = shelephant.cli.shelephant_get:main
    - shelephant_merge = shelephant.cli.shelephant_merge:main
    - shelephant_parse = shelephant.cli.shelephant_parse:main
    - shelephant_hostinfo = shelephant.cli.shelephant_hostinfo:main
    - shelephant_cp = shelephant.cli.shelephant_cp:main
    - shelephant_mv = shelephant.cli.shelephant_mv:main
    - shelephant_rm = shelephant.cli.shelephant_rm:main
    - shelephant_send = shelephant.cli.shelephant_send:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - docopt
    - click
    - pyyaml
    - mergedeep
    - tqdm
    - numpy

test:
  imports:
    - shelephant
  commands:
    - shelephant_checksum --help
    - shelephant_dump --help
    - shelephant_extract --help
    - shelephant_get --help
    - shelephant_merge --help
    - shelephant_parse --help
    - shelephant_hostinfo --help
    - shelephant_cp --help
    - shelephant_mv --help
    - shelephant_rm --help
    - shelephant_send --help

about:
  home: https://github.com/tdegeus/shelephant
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Copy files with a smart memory to skip unneeded action
  description: Copy files with a smart memory to skip unneeded action
  doc_url: https://github.com/tdegeus/shelephant
  dev_url: https://github.com/tdegeus/shelephant

extra:
  recipe-maintainers:
    - tdegeus
