{% set name = "shelephant" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21bd911b7db9ca9c91165cc0ee7948385747582be38d754fcbb5f2214f004dc2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shelephant_checksum = shelephant.cli.shelephant_checksum:main
    - shelephant_dump = shelephant.cli.shelephant_dump:main
    - shelephant_extract = shelephant.cli.shelephant_extract:main
    - shelephant_get = shelephant.cli.shelephant_get:main
    - shelephant_merge = shelephant.cli.shelephant_merge:main
    - shelephant_parse = shelephant.cli.shelephant_parse:main
    - shelephant_hostinfo = shelephant.cli.shelephant_hostinfo:main
    - shelephant_cp = shelephant.cli.shelephant_cp:main
    - shelephant_mv = shelephant.cli.shelephant_mv:main
    - shelephant_rm = shelephant.cli.shelephant_rm:main
    - shelephant_send = shelephant.cli.shelephant_send:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
  run:
    - python >=3
    - click
    - pyyaml
    - mergedeep
    - tqdm
    - numpy

test:
  imports:
    - shelephant
  commands:
    - shelephant_checksum --version
    - shelephant_dump --version
    - shelephant_extract --version
    - shelephant_get --version
    - shelephant_merge --version
    - shelephant_parse --version
    - shelephant_hostinfo --version
    - shelephant_cp --version
    - shelephant_mv --version
    - shelephant_rm --version
    - shelephant_send --version

about:
  home: https://github.com/tdegeus/shelephant
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Copy files with a smart memory to skip unneeded action
  description: Copy files with a smart memory to skip unneeded action
  doc_url: https://github.com/tdegeus/shelephant
  dev_url: https://github.com/tdegeus/shelephant

extra:
  recipe-maintainers:
    - tdegeus
